steps:
  - id: Build and push to Artifact Registry
    name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - >-
        docker run --network=cloudbuild -v /workspace:/workspace
        gcr.io/kaniko-project/executor:latest
        --destination=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
        --destination=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
        --cache=true
        --cache-ttl=336h

  - id: Deploy to Cloud Run
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - "--region=$_DEPLOY_REGION"
      - "--quiet"

serviceAccount: projects/local-first-476300/serviceAccounts/cloud-build-sa@local-first-476300.iam.gserviceaccount.com

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: webapp-0p5dev
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: open-source-application-images
  _AR_PROJECT_ID: local-first-476300

tags:
  - development
  - webapp
  - 0p5.dev
