name: 0p5.dev
networks:
  0p5dev:
    driver: bridge
    name: 0p5dev
services:
  webapp:
    image: node:24-alpine
    container_name: 0p5.dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true
    entrypoint: [ "sh", "-c" ]
    command: [ "npm install && npm run dev" ]
    networks:
      - 0p5dev
    env_file:
      - .env
    environment:
      # NUXT_CONTROLLER_BASE_URL: http://controller:8080/api/v1
      # NUXT_PUBLIC_EVENT_SOURCE_BASE_URL: http://localhost:8080/api/v1
      NUXT_CONTROLLER_BASE_URL: https://staging.controller.0p5.dev/api/v1
      NUXT_PUBLIC_EVENT_SOURCE_BASE_URL: https://staging.controller.0p5.dev/api/v1
      NUXT_PUBLIC_SUPABASE_URL: ${NUXT_PUBLIC_SUPABASE_URL}
      NUXT_PUBLIC_SUPABASE_API_KEY: ${NUXT_PUBLIC_SUPABASE_API_KEY}
      NUXT_PUBLIC_GITHUB_API_TOKEN: ${NUXT_PUBLIC_GITHUB_API_TOKEN}
      NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    user: "${UID-1000}:${GID-1000}"
